let sessionId="", teamId="", gameType="", currentRound=null, timerInterval=null, timerSeconds=300;
function go(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});if(id==='ranking')rank();}
function selectSession(id){sessionId=id;document.querySelectorAll('#login .buttons button').forEach(b=>b.classList.remove('active'));event.target.classList.add('active');}
function login(){const code=document.getElementById('accessCode').value.trim().toUpperCase();if(!sessionId){alert('Selecciona primero el día.');return}const teams=DATA.sessions[sessionId].teams;let found=null;Object.entries(teams).forEach(([k,t])=>{if(t.code===code)found=k});if(!found){alert('Código no válido para esta partida.');return}teamId=found;renderTeamHome();go('teamHome');}
function renderTeamHome(){const t=DATA.sessions[sessionId].teams[teamId];document.getElementById('teamHeader').innerHTML=`<span>${DATA.sessions[sessionId].label}</span><h2>${t.name}</h2><p>Panel privado. No muestres esta pantalla al equipo contrario.</p>`;document.getElementById('members').innerHTML=t.members.join('<br>');}
function openGame(type){gameType=type;const g=DATA[type];document.getElementById('gameHeader').innerHTML=`<span>${DATA.sessions[sessionId].label}</span><h2>${g.title}</h2><p>Duración total: ${g.duration}</p>`;document.getElementById('phaseList').innerHTML=g.phases.map(p=>`<div class="phase"><span>${p.name}</span><b>${p.minutes}'</b></div>`).join('');renderRounds();go('rounds');}
function renderRounds(){const list=document.getElementById('roundList');list.innerHTML='';DATA[gameType].rounds.forEach(r=>{let role=r.seller===teamId?'VENDEDOR':r.client===teamId?'CLIENTE':'JURADO';let div=document.createElement('div');div.className='round';div.innerHTML=`<h3>${r.title}</h3><p><span class="roleTag">${role}</span></p><button onclick="openPanel('${r.id}')">Abrir mi panel</button>`;list.appendChild(div)});}
function openPanel(id){currentRound=DATA[gameType].rounds.find(r=>r.id===id);const scenario=DATA.cases[currentRound.seller];let role=currentRound.seller===teamId?'seller':currentRound.client===teamId?'client':'judge';let html='';if(role==='seller')html=sellerPanel(scenario);else if(role==='client')html=clientPanel(scenario);else html=judgePanel(scenario);document.getElementById('privatePanel').innerHTML=html;document.getElementById('scoreContext').textContent=`${currentRound.title} · Puntúa al vendedor: Equipo ${currentRound.seller}`;go('panel');}
function sellerPanel(s){return `<div class="privateHero"><span>Tu rol: VENDEDOR</span><h2>${s.segment} · ${s.title}</h2><p>${s.sellerGoal}</p></div><div class="briefBlock"><h3>Información del caso</h3><ul><li>${s.opportunity}</li><li>Señales: ${s.signals.join(', ')}</li></ul></div><div class="briefBlock"><h3>Herramienta de preparación</h3><div class="toolGrid"><div class="tool"><b>1. Situación:</b> ¿Qué está pasando?</div><div class="tool"><b>2. Riesgo:</b> ¿Qué puede fallar?</div><div class="tool"><b>3. Impacto:</b> ¿Qué coste tiene para el cliente?</div><div class="tool"><b>4. Pregunta:</b> ¿Qué pregunta abre conversación?</div><div class="tool"><b>5. Compromiso:</b> ${s.commitment}</div></div></div>${gameType==='negotiation'?`<div class="briefBlock danger"><h3>Objeción probable</h3><p><b>“${s.objection}”</b></p><p>Usa: reconocer → profundizar → neutralizar → resolver.</p></div>`:''}`;}
function clientPanel(s){return `<div class="privateHero client"><span>Tu rol: CLIENTE</span><h2>${s.segment} · ${s.title}</h2><p>${s.clientRole}</p></div><div class="briefBlock danger"><h3>Objeción obligatoria</h3><p><b>“${s.objection}”</b></p></div><div class="briefBlock secret"><h3>Información oculta</h3><ul>${s.clientSecret.map(x=>`<li>${x}</li>`).join('')}</ul><p><b>Regla:</b> no reveles esto si el vendedor no pregunta bien.</p></div><div class="briefBlock"><h3>Qué te haría avanzar</h3><p>${s.commitment}</p></div>`;}
function judgePanel(s){return `<div class="privateHero judge"><span>Tu rol: JURADO</span><h2>Observa sin intervenir</h2><p>Evalúa si el vendedor mueve la conversación de precio a valor.</p></div><div class="briefBlock"><h3>Qué debes observar</h3><ul><li>¿Abre con hipótesis o con producto?</li><li>¿Reconoce la objeción sin defenderse?</li><li>¿Hace preguntas útiles?</li><li>¿Descubre información oculta?</li><li>¿Reencuadra precio hacia coste, riesgo e impacto?</li><li>¿Cierra un compromiso concreto?</li></ul></div><button class="primary" onclick="go('score')">Ir a scorecard</button>`;}
function updateScore(){let total=0;[1,2,3,4,5,6].forEach(n=>{let el=document.getElementById('s'+n);let b=el?.parentElement.querySelector('b');if(el){total+=Number(el.value);if(b)b.textContent=el.value}});document.getElementById('total').textContent=total+'/60';}
function copyScore(){updateScore();let text=`${DATA.sessions[sessionId].label}\n${gameType==='prospection'?'Prospección':'Negociación'}\n${currentRound?currentRound.title:''}\nJurado: Equipo ${teamId}\nPuntuación: ${document.getElementById('total').textContent}`;navigator.clipboard.writeText(text).then(()=>alert('Puntuación copiada.'))}
function startTimer(min){timerSeconds=min*60;clearInterval(timerInterval);timerInterval=setInterval(()=>{timerSeconds--;renderTimer();if(timerSeconds<=0){clearInterval(timerInterval);alert('Tiempo terminado')}},1000);renderTimer();}
function pauseTimer(){clearInterval(timerInterval)}
function resetTimer(){clearInterval(timerInterval);timerSeconds=300;renderTimer()}
function renderTimer(){let m=String(Math.floor(timerSeconds/60)).padStart(2,'0');let s=String(timerSeconds%60).padStart(2,'0');let el=document.getElementById('timer');if(el)el.textContent=m+':'+s;}
function rank(){let arr=[['A',+document.getElementById('rA').value||0],['B',+document.getElementById('rB').value||0],['C',+document.getElementById('rC').value||0],['D',+document.getElementById('rD').value||0]].sort((a,b)=>b[1]-a[1]);document.getElementById('board').innerHTML=arr.map((x,i)=>`<div class="row"><div class="pos">#${i+1}</div><div>Equipo ${x[0]}</div><div class="score">${x[1]}</div></div>`).join('')}
updateScore();renderTimer();