let selectedGame="", selectedTeam="", selectedRound=null;
function screen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});if(id==='ranking')rank()}
function init(){renderGames();updateScore();rank()}
function renderGames(){const box=document.getElementById('gameButtons');box.innerHTML='';Object.entries(DATA.partidas).forEach(([key,g])=>{const b=document.createElement('button');b.textContent=g.label;b.onclick=()=>selectGame(key);box.appendChild(b)});}
function selectGame(key){selectedGame=key;selectedTeam="";document.querySelectorAll('#gameButtons button').forEach(b=>b.classList.toggle('active',b.textContent===DATA.partidas[key].label));renderTeams();document.getElementById('members').innerHTML='';}
function renderTeams(){const box=document.getElementById('teamButtons');box.innerHTML='';Object.entries(DATA.partidas[selectedGame].teams).forEach(([k,t])=>{const b=document.createElement('button');b.textContent=k+' · '+t.name.split('·')[1].trim();b.onclick=()=>selectTeam(k);box.appendChild(b)})}
function selectTeam(k){selectedTeam=k;document.querySelectorAll('#teamButtons button').forEach(b=>b.classList.toggle('active',b.textContent.startsWith(k+' ·')));const t=DATA.partidas[selectedGame].teams[k];document.getElementById('members').innerHTML='<b>'+t.name+'</b><br>'+t.members.join('<br>');renderRounds()}
function renderRounds(){const list=document.getElementById('roundList');document.getElementById('roundTitle').textContent=DATA.partidas[selectedGame].label;list.innerHTML='';DATA.rounds.forEach(r=>{let role=r.seller===selectedTeam?'VENDEDOR':r.client===selectedTeam?'CLIENTE':'JURADO';let div=document.createElement('div');div.className='round';div.innerHTML=`<h3>${r.title}</h3><p><span class="roleTag">${role}</span></p><button onclick="openBrief(${r.id})">Abrir briefing</button>`;list.appendChild(div)})}
function openBrief(id){selectedRound=DATA.rounds.find(r=>r.id===id);const s=DATA.scenarios[selectedRound.seller];let role=selectedRound.seller===selectedTeam?'seller':selectedRound.client===selectedTeam?'client':'judge';let html='';if(role==='seller'){html=`<div class="brief seller"><span class="roleTag">ROL: VENDEDOR</span><h3>${s.sellerTitle}</h3><p><b>Misión:</b> ${s.sellerMission}</p><ul>${s.sellerContext.map(x=>'<li>'+x+'</li>').join('')}</ul><p><b>Objetivo:</b> abrir conversación, gestionar objeción y cerrar compromiso.</p></div>`}else if(role==='client'){html=`<div class="brief client"><span class="roleTag">ROL: CLIENTE</span><h3>${s.clientRole}</h3><p><b>Objeción obligatoria:</b></p><p><strong>“${s.priceObjection}”</strong></p><p><b>Información oculta:</b></p><ul>${s.clientHidden.map(x=>'<li>'+x+'</li>').join('')}</ul><p>No entregues toda la información al principio. Haz que el vendedor pregunte.</p></div>`}else{html=`<div class="brief judge"><span class="roleTag">ROL: JURADO</span><h3>Observa y puntúa</h3><p>Evalúa al equipo vendedor. No intervengas durante la escena.</p><ul><li>¿Llega con hipótesis?</li><li>¿Reconoce la objeción?</li><li>¿Profundiza?</li><li>¿Neutraliza?</li><li>¿Reencuadra valor?</li><li>¿Cierra compromiso?</li></ul></div>`}document.getElementById('briefingContent').innerHTML=html;screen('briefing')}
function updateScore(){let total=0;[1,2,3,4,5,6].forEach(n=>{let el=document.getElementById('s'+n);let b=el?.parentElement.querySelector('b');if(el){total+=Number(el.value);if(b)b.textContent=el.value}});document.getElementById('total').textContent=total+'/60'}
function copyScore(){updateScore();let total=document.getElementById('total').textContent;let text=`${DATA.partidas[selectedGame]?.label||''}\n${selectedRound?selectedRound.title:''}\nJurado: Equipo ${selectedTeam}\nPuntuación: ${total}`;navigator.clipboard.writeText(text).then(()=>alert('Puntuación copiada.'))}
function rank(){let arr=[['A',+document.getElementById('rA').value||0],['B',+document.getElementById('rB').value||0],['C',+document.getElementById('rC').value||0],['D',+document.getElementById('rD').value||0]].sort((a,b)=>b[1]-a[1]);document.getElementById('board').innerHTML=arr.map((x,i)=>`<div class="row"><div class="pos">#${i+1}</div><div>Equipo ${x[0]}</div><div class="score">${x[1]}</div></div>`).join('')}
init();